# На какой группе серверов
- hosts: webservers
  vars:
    root_dir: /usr/share/nginx/html
    nginx_port: 80

  tasks:
    - name: install redis
      ansible.builtin.apt: # имя модуля Ansible
        name: redis-server
        state: present
        update_cache: yes
      become: yes
      tags: [redis]

    - name: remove redis server
      # apt-get remove redis-server
      ansible.builtin.apt:
        name: redis-server
        state: absent
      become: yes
      tags: [redis, remove-app]

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes
      tags: [linux-config, built-app]

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      become: yes
      tags: [nginx, built-app]

    - name: remove nginx
      ansible.builtin.apt:
        name: nginx
        state: absent
      become: yes
      tags: [nginx, remove-app]

    - name: update nginx config
      ansible.builtin.template:
        src: nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
      become: yes
      notify:
        - restart nginx
      tags: [nginx, built-app]

    - name: copy html
      ansible.builtin.template:
        src: html/index.html
        dest: "{{ root_dir }}/index.html"
      become: yes
      tags: [nginx, built-app]



  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
